// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlkdNnXA7K6So2GuCVmKKeRvltLBUIBP4',
    appId: '1:709245310212:web:0eb8f509b5aad260c8ac51',
    messagingSenderId: '709245310212',
    projectId: 'chat-b58db',
    authDomain: 'chat-b58db.firebaseapp.com',
    storageBucket: 'chat-b58db.firebasestorage.app',
    measurementId: 'G-3KQKSQB9RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRnXkoDGvIV46Q1Ojo9tx7odMTZQesyw',
    appId: '1:709245310212:android:e24bb6f94423c7abc8ac51',
    messagingSenderId: '709245310212',
    projectId: 'chat-b58db',
    storageBucket: 'chat-b58db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzPl-1jVEWQlbq4k2kXeFfzYRK11Zi3D0',
    appId: '1:709245310212:ios:310cd0fb4b6857acc8ac51',
    messagingSenderId: '709245310212',
    projectId: 'chat-b58db',
    storageBucket: 'chat-b58db.firebasestorage.app',
    iosBundleId: 'com.aymnman.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzPl-1jVEWQlbq4k2kXeFfzYRK11Zi3D0',
    appId: '1:709245310212:ios:310cd0fb4b6857acc8ac51',
    messagingSenderId: '709245310212',
    projectId: 'chat-b58db',
    storageBucket: 'chat-b58db.firebasestorage.app',
    iosBundleId: 'com.aymnman.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlkdNnXA7K6So2GuCVmKKeRvltLBUIBP4',
    appId: '1:709245310212:web:6399dca2cc745d01c8ac51',
    messagingSenderId: '709245310212',
    projectId: 'chat-b58db',
    authDomain: 'chat-b58db.firebaseapp.com',
    storageBucket: 'chat-b58db.firebasestorage.app',
    measurementId: 'G-9PVDHLL2YC',
  );
}
